## IGNORE THIS NOTEBOOK
I am still working on getting a Qiskit tutorial set up so this isn't quite ready for a walk-thru yet.

## Summary of Quantum Operations
In this section we will go into the different operations that are available in Qiskit Terra. These :
- Single-qubit quantum gates
- Multi-qubit quantum gates
- Measurements 
- Resent 
- Conditionals 
- State initialization

We will also show you how to use the three different simulators:
- unitary_simulator 
- qasm_simulator
- statevector_simulator

In [1]:
# Useful additional packages
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

In [2]:
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

## Single Qubit Quantum States
A single qubit quantum state can be written as 
<center> $|\psi\rangle = \alpha |0\rangle + \beta |1\rangle$ </center>
where $\alpha$ and $\beta$ are complex numbers. In a measurement the probability of the bit being in $|0\rangle$ is $|\alpha|^{2}$ and $|1\rangle$ is $|\beta|^{2}$. As a vector this is
<center> $|\psi\rangle = \begin{pmatrix} \alpha \\ \beta \end{pmatrix} $</center>
Note due to conservation of probability $|\alpha|^{2}+|\beta|^{2}=1$ and since global phase is undetectable $|\psi\rangle := e^{i\delta}|\psi\rangle$ we only require two real numbers to describe a single qubit quantum state.

A convenient representation is
<center> $|\psi\rangle = \cos{(\theta/2)}|0\rangle + \sin{(\theta/2)}e^{i\phi}|1\rangle$ </center>
where $0\leq \phi \leq 2\pi$. From this it is clear that there is a one-to-one correspondence between qubit states $(\mathbb{C}^{2})$ and the points on the surface of a unit sphere $(\Re^{3})$. This is called the Block sphere representation of a qubit state.

Quantum gates/operations are usually represented as matrices. A gate which acts on a qubit is represent by a $2\times2$ unitary matrix $U$. The action of the quantum gate is found by multiplying the matrix representing the gate with the vector which represents the quantum state. 
<center> $|\psi^{\prime}\rangle = U|\psi\rangle$ </center>
A general unitary operator must be able to take the $|0\rangle$ to the above states. That is 
<center> $U = \begin{pmatrix} \cos{(\theta/2)} & a \\ e^{i\phi}\sin{(\theta/2)} & b \end{pmatrix}$ </center>

where $a$ and $b$ are complex numbers constrained such that $U^{\dagger}U=I$ for all $0\leq \theta \leq \pi$ and $0\leq \phi \leq 2\pi$. This gives 3 constraints and as such $a\rightarrow -e^{i\lambda}\sin{(\theta/2)}$ and $b\rightarrow e^{i\lambda+i\phi}\cos{(\theta/2)}$ where $0\leq\lambda\leq 2 \pi$ giving  <br>

<center> $U = \begin{pmatrix} \cos{(\theta/2)} & -e^{i\lambda}\sin{(\theta/2)} \\ e^{i\phi}\sin{(\theta/2)} & e^{i\lambda+i\phi}\cos{(\theta/2)} \end{pmatrix} $ </center>

This is the most general form of a signle qubit unitary operator. 

## Single-Qubit Gates
The single-qubit gates available are:
- Unitary gates 
- Identity gate
- Pauli gates
- Clifford gates
- C3 gates
- Standard rotation gates

We have provided a backend: `unitary_simulator` to allow you to calculate the unitary matrices.

In [3]:
q = QuantumRegister(1)

### Unitary Gates
In Qiskit we give you access to the general unitary operator using the u3 gate  
<br>
<center> $u3(\theta,\phi,\lambda) = U(\theta,\phi,\lambda)$ </center>

In [4]:
qc = QuantumCircuit(q)
qc.u3(pi/2,pi/2,pi/2,q)
qc.draw()

In [5]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j   ,  0.   -0.707j],
       [ 0.   +0.707j, -0.707+0.j   ]])

The $u1(\lambda)=u3(0,0,\lambda)$ gate has the matrix form
<br> <center> $u1(\lambda)=\begin{pmatrix} 1 & 0 \\ 0 & e^{i\lambda} \end{pmatrix}$ </center>
which is useful as it allows us to apply a quantum phase.

In [6]:
qc = QuantumCircuit(q)
qc.u1(pi/2,q)
qc.draw()

In [7]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

### Identity Gate
The identity gate is $Id=u0(1)$.

In [8]:
qc = QuantumCircuit(q)
qc.iden(q)
qc.draw()

In [9]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

### Pauli Gates
#### $\chi$: bit-flipgate
The bit-flip gate $\chi$ is defined as:
<center> $\chi = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix} = u3(\pi,0,\pi)$ </center>


In [10]:
qc = QuantumCircuit(q)
qc.x(q)
qc.draw()

In [11]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

#### $Y$: bit- and phase-flip gate
The $Y$ gate is defined as:
<center> $Y=\begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix} = u3(\pi,\pi/2,\pi/2) $ </center>


In [12]:
qc = QuantumCircuit(q)
qc.y(q)
qc.draw()

In [13]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

#### $Z$: phase-flip gate
The phase flip gate $Z$ is defined as:
<center> $ Z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix} = u1(\pi)$ </center>


In [14]:
qc = QuantumCircuit(q)
qc.z(q)
qc.draw()

In [15]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

### Clifford Gates
#### Hadamard Gate
<center> $ H = \frac{1}{\sqrt{2}}\begin{pmatrix}1 & 1 \\ 1 & -1\end{pmatrix} = u2(0,\pi)$</center>


In [16]:
qc = QuantumCircuit(q)
qc.h(q)
qc.draw()

In [17]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j,  0.707+0.j],
       [ 0.707+0.j, -0.707+0.j]])

#### $S$ (or, $\sqrt{Z}$ phase) gate
<center> $ S = \begin{pmatrix} 1 & 0 \\ 0 & i \end{pmatrix} = u1)\pi/2) $ </center>


In [18]:
qc = QuantumCircuit(q)
qc.s(q)
qc.draw()

In [19]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

#### $S^{\dagger}$ (or, conjugate of $\sqrt{Z}$ phase) gate
<center> $ S^{\dagger} = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix} = u1(-\pi/2) $ </center>


In [20]:
qc = QuantumCircuit(q)
qc.sdg(q)
qc.draw()

In [21]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.-1.j]])

### C3 Gates
#### $T$ (or, $\sqrt{S}$ phase) gate
<center> $ T = \begin{pmatrix} 1 & 0 \\ 0 & e^{i\pi/4} \end{pmatrix} = u1(\pi/4) $ </center>


In [22]:
qc = QuantumCircuit(q)
qc.t(q)
qc.draw()

In [23]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707+0.707j]])

#### $T^{\dagger}$ (or, conjugate of $\sqrt{S}$ phase) gate
<center> $T^{\dagger} = \begin{pmatrix} 1 & 0 \\ 0 & e^{-\pi/4} \end{pmatrix} = u1(-\pi/4) $ </center>
They can be added as below.

In [24]:
qc = QuantumCircuit(q)
qc.tdg(q)
qc.draw()

In [25]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.707-0.707j]])

### Standard Rotations
The standard rotation gates are those that define rotations around the Pauli's $P=\{ X,Y,Z\}$. They are defined as 
<br> <br>

<center> $R_{P}(\theta) = \exp(-i\theta P/2) = \cos(\theta/2)I - i\sin(\theta/2)P$ </center>

#### Rotation around X-axis
<center> $ R_{x}(\theta) = \begin{pmatrix} \cos{(\theta/2)} -i\sin{(\theta/2)} \\ -i\sin{(\theta/2)} & \cos{(\theta/2)} \end{pmatrix} = u3(\theta,-\pi/2,\pi/2)$</center>

In [26]:
qc = QuantumCircuit(q)
qc.rx(pi/2,q)
qc.draw()

In [27]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[0.707+0.j   , 0.   -0.707j],
       [0.   -0.707j, 0.707+0.j   ]])

#### Rotation about Y-axis
<center> $ R_{y}(\theta) = \begin{pmatrix} \cos{(\theta/2)} & -sin{(\theta/2)} \\ \sin{(\theta/2)} & \cos{(\theta/2)} \end{pmatrix} = u3(\theta,0,0)$</center>

In [28]:
qc = QuantumCircuit(q)
qc.ry(pi/2,q)
qc.draw()

In [29]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[ 0.707+0.j, -0.707+0.j],
       [ 0.707+0.j,  0.707+0.j]])

#### Rotation around X-axis 
<center> $R_{z}(\phi) = \begin{pmatrix} e^{-i\phi/2} & 0 \\ 0 & e^{i\phi/2} \end{pmatrix} \equiv u1(\phi)$ </center>
Note here we have used an equivalent as it is different to u1 by a global phase $e^{-\phi/2}$.

In [30]:
qc = QuantumCircuit(q)
qc.rz(pi/2,q)
qc.draw()

In [31]:
job = execute(qc, backend)
job.result().get_unitary(qc, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

Note this is different due only to a global phase.

## Multi-Qubit Gates
### Mathematical Preliminaries 
The space of a quantum computer grows exponentially with the number of qubbits. For $n$ qubits the complex vector space has dimensions $d=2^{n}$. To describe states of a multi-qubit system, the tensor product is used to "glue together" operators and basis vectors.

Let's start by considering a 2-qubit system. Given two operators $A$ and $B$ that each act on one qubit, the joint operator $A\otimes B$ acting on two qubits is
<center> $A\otimes B = \begin{pmatrix} A_{00}\begin{pmatrix} B_{00} & B_{01} \\ B_{10} & B_{11} \end{pmatrix} & A_{01} \begin{pmatrix} B_{00} & B_{01} \\ B_{10} & B_{11} \end{pmatrix} \\ A_{10} \begin{pmatrix} B_{00} & B_{01} \\ B_{10} & B_{11} \end{pmatrix} & A_{11} \begin{pmatrix} B_{00} & B_{01} \\ B_{10} & B_{11} \end{pmatrix} \end{pmatrix} $ </center>

where $A_{jk}$ and $B_{lm}$ are the matrix elements of $A$ and $B$, respectively. 

Analogously, the basis vectors for the 2-qubit system are formed using the tensor product of basis vectors for a single qubit:
<center> $ \begin{matrix} |00\rangle = \begin{pmatrix} 1\begin{pmatrix} 1 \\ 0 \end{pmatrix} \\ 0 \begin{pmatrix} 1 \\ 0 \end{pmatrix} \end{pmatrix} = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0 \end{pmatrix} & |01\rangle = \begin{pmatrix} 1\begin{pmatrix} 0 \\ 1 \end{pmatrix} \\ 0 \begin{pmatrix} 0 \\ 1 \end{pmatrix} \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix} \\|10\rangle = \begin{pmatrix} 0\begin{pmatrix} 1 \\ 0 \end{pmatrix} \\ 1 \begin{pmatrix} 1 \\ 0 \end{pmatrix} \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 1 \\ 0 \end{pmatrix} & |11\rangle = \begin{pmatrix} 0\begin{pmatrix} 0 \\ 1 \end{pmatrix} \\ 1 \begin{pmatrix} 0 \\ 1 \end{pmatrix} \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 1 \end{pmatrix} \end{matrix} $ </center>

Note we've introduced a shorthand for the tensor product of basis vectors, wherein $|0\rangle \otimes |0\rangle$ is written as $|00\rangle$. The state of an $n$-qubit system can be described using the $n$-fold tensor product of single-qubit basis vectors. Notice that the vectors for a 2-qubit system are 4-dimensional; in general, the basis vectors of an $n$-qubit system are $2^{n}$-dimensional, as noted earlier.

### Basis vector ordering in Qiskit
Within the physics community, the qubits of a multi-qubit systems are typically ordered with the first qubit on the left-most side of the tensor product and the last qubit on the right-most side. For instance, if the first qubit is in state $|0\rangle$ and the second is in state $|1\rangle$, their joint state would be $|01\rangle$. Qiskit uses a slightly different ordering of the qubits, in which the qubits are presented from the most significant bit (MSB) on the left to the least significant bit (LSB) on the right (big-endian). This is similar to bitstring representation on classical computres, and enables easy conversion from bitstrings to integers after measurements are performed. For the example just given, the joint state would be represented at $|10\rangle$. Importabtly, _this change in the representation of multi-qubit states affects the way multi-qubit gates are represented in Qiskit_, as discussed below.

The representation used in Qiskit enumerates the basis vectors in increasing order of the integers they represent. For instance, the basis vectors for a 2-qubit system would be ordered as $|00\rangle$, $|01\rangle$, $|10\rangle$, and $|11\rangle$. Thinking of the basis vectors as bit strings, they encode the integers 0, 1, 2 and 3, respectively.

### Controlled Operations on qubits
A common multi-qubit gate involes the application of a gate to one qubit, conditioned on the state of another qubit. For instance, we might want to flip the state of the second qubit when the first qubit is in $|0\rangle$. Such gates are known as _controlled gates_. The standard multi-qubit gates consist of two-qubit gates and three-qubit gates. The two-qubit gates are:
- controlled Pauli gates 
- controlled Hadamard gates
- controlled rotation gates
- controlled phase gate
- controlled u3 gate
- swap gate 

The three-qubit gates are:
- Toffoli gate
- Fredkin gate

### Two-qubit gates
Most of the two-gates are of the controlled type (the SWAP gate being the exception). In general, a controlled two-qubit gate $C_{U}$ acts to apply the single-qubit unitary $U$ to the second qubit when the state of the first qubit is in $|1\rangle$. Supposed $U$ has a matrix representation 
<center> $U=\begin{pmatrix} u_{00} & u_{01} \\ u_{10} & u_{11} \end{pmatrix} $ </center>